api_platform:
    title: Confoo 2024 - Lockers System
    description: |
        Hello on my **API** application
    show_webby: false
    version: 1.0.0
    formats:
        jsonld: ['application/ld+json']
        json: ['application/json']
    docs_formats:
        jsonld: ['application/ld+json']
        jsonopenapi: ['application/vnd.openapi+json']
        html: ['text/html']
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true
            rfc_7807_compliant_errors: true
    event_listeners_backward_compatibility_layer: false
    keep_legacy_inflector: false
    path_segment_name_generator: api_platform.metadata.path_segment_name_generator.dash

    swagger:
        api_keys:
            basic_auth: # <-- arbitrary name for the security scheme
                type: header
                name: Authorization
